python setup.cgi -u assr1 -p assr1
python setup.cgi -u assr2 -p assr2
python setup.cgi -u assr3 -p assr3
python setup.cgi -u assr4 -p assr4
python setup.cgi -u assr5 -p assr5
python setup.cgi -u assr6 -p assr6
python setup.cgi -u assr7 -p assr7
python setup.cgi -u assr8 -p assr8
python setup.cgi -u assr9 -p assr9
python setup.cgi -u assr10 -p assr10
python setup.cgi -u assr11 -p assr11
python setup.cgi -u assr12 -p assr12
python setup.cgi -u assr13 -p assr13
python setup.cgi -u assr14 -p assr14
python setup.cgi -u assr15 -p assr15
python setup.cgi -u assr16 -p assr16
python setup.cgi -u assr17 -p assr17
python setup.cgi -u assr18 -p assr18
python setup.cgi -u assr19 -p assr19
python setup.cgi -u assr20 -p assr20
python setup.cgi -u jiyun -p jiyun
python setup.cgi -u grace -p grace
python setup.cgi -u grace1 -p grace1
python setup.cgi -u grace2 -p grace2
python setup.cgi -u admin -p admin
python setup.cgi -u ian -p ian
python setup.cgi -u ian1 -p ian1
python setup.cgi -u ian2 -p ian2
